### ISSUE TITLE
new postprocessor problems

### ISSUE THREAD

**Issue by lagleki** [lojban/ilmentufa#5] opened 2016-04-16 10:47 UTC
```broda zei coi``` in "+selmaho" mode doesn't show names of word classes

**Comment by Ilmen-vodhr** [comment] 2016-04-17 21:11
The cause of this issue was the following:
During the conversion of ECMAScript 6 arrow notations to legacy function definitions, I failed to add the 'return' keyword, resulting in the node pruning filter function always returning 'undefined'.
This is now fixed.
Thank you!

**Closed by Ilmen-vodhr** 2016-04-17 21:11 UTC
